apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjoKCXsKCQkiZ2hjci5pbyI6CgkJewoJCQkiYXV0aCI6ICJhV3h6WlhKblpXVjJPbWRvY0Y5NWRreEVRMUYzUTI5SVZtZFdNRXhMTkdoQlUxZ3piak13TjFBNWJIb3paazg1WTFjPSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiZGVidWciOiB7CgkJCSJob29rcyI6ICJleGVjIgoJCX0sCgkJInNjb3V0IjogewoJCQkiaG9va3MiOiAicHVsbCxidWlsZHggYnVpbGQiCgkJfQoJfSwKCSJmZWF0dXJlcyI6IHsKCQkiaG9va3MiOiAidHJ1ZSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
