{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.proxyService.app.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.proxyService.app.name }}
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.proxyService.app.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.proxyService.app.name }}
    spec:
      containers:
      - name: {{ .Values.proxyService.app.name }}
        image: {{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}
        imagePullPolicy: {{ .Values.proxyService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.proxyService.service.targetPort }}
        env:
        - name: PORT
          value: "{{ .Values.proxyService.service.targetPort }}"
        - name: ASPNETCORE_URLS
          value: "http://+:{{ .Values.proxyService.service.targetPort }}"
        envFrom:
        - configMapRef:
            name: cinemaabyss-config
        - secretRef:
            name: cinemaabyss-secrets
        resources:
          {{- toYaml .Values.proxyService.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /api/proxy/health
            port: {{ .Values.proxyService.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/proxy/health
            port: {{ .Values.proxyService.service.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxyService.app.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.proxyService.app.name }}
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.proxyService.app.name }}
  ports:
  - port: {{ .Values.proxyService.service.port }}
    targetPort: {{ .Values.proxyService.service.targetPort }}
  type: {{ .Values.proxyService.service.type }}
{{- end }}